In [1]:
import pandas as pd 
from pathlib import Path

In [2]:
file_path = Path("C:\\Users\\Anna May\\Downloads\\FANRBF\\TVET_Stats_Analysis\\tvet_statistics_analysis\\data\\raw\\raw_tvet_data.xls")

excel = pd.ExcelFile(file_path)
print(excel.sheet_names)

['Assessed and Certified Overall', 'Assessed and Certified CACW', 'Mandatory Assessment', 'AC and CA', 'New AC and CA', 'PCT Monitoring', 'Establishment of AC']

In [3]:
raw = pd.read_excel(file_path, header=None)
display(raw.head(12))

,0,1,2,3,4,5,6,7,8
0,Number of Persons Assessed and Certified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"January 01 to 31, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Region,Province,Assessed,NaN,NaN,Assessed,NaN,NaN,Cert. Rate
4,NaN,NaN,Female,Male,Total,Female,Male,Total,NaN
5,I,Ilocos Norte,21,103,124,17,95,112,0.9032
6,NaN,Ilocos Sur,23,174,197,23,158,181,0.9188
7,NaN,La Union,93,219,312,91,208,299,0.9583
8,NaN,Pangasinan,510,1040,1550,473,969,1442,0.9303
9,I Total,NaN,647,1536,2183,604,1430,2034,0.9317
10,II,Cagayan,152,404,556,151,396,547,0.9838
11,NaN,Isabela,93,138,231,88,137,225,0.974

In [4]:
columns = [
    "region",
    "province",
    "assessed_female",
    "assessed_male",
    "assessed_total",
    "certified_female",
    "certified_male",
    "certified_total",
    "certification_rate"
]

df = raw.iloc[5:, :9].copy()
df.columns = columns

display(df.head())

,region,province,assessed_female,assessed_male,assessed_total,certified_female,certified_male,certified_total,certification_rate
5,I,Ilocos Norte,21,103,124,17,95,112,0.9032
6,NaN,Ilocos Sur,23,174,197,23,158,181,0.9188
7,NaN,La Union,93,219,312,91,208,299,0.9583
8,NaN,Pangasinan,510,1040,1550,473,969,1442,0.9303
9,I Total,NaN,647,1536,2183,604,1430,2034,0.9317

In [5]:
#text formatting for region and province columns
for col in ["region", "province"]:
    df[col] = df[col].astype(str).str.strip()

print(df.head())

    region      province assessed_female assessed_male assessed_total  \
5        I  Ilocos Norte              21           103            124
6      nan    Ilocos Sur              23           174            197
7      nan      La Union              93           219            312
8      nan    Pangasinan             510          1040           1550
9  I Total           nan             647          1536           2183

  certified_female certified_male certified_total certification_rate
5               17             95             112             0.9032
6               23            158             181             0.9188
7               91            208             299             0.9583
8              473            969            1442             0.9303
9              604           1430            2034             0.9317

In [6]:
#dropping rows
df = df.dropna(how="all")
df = df[df['province'].notna() & df['province'].ne("nan")].copy()

print(df)

             region              province assessed_female assessed_male  \
5                 I          Ilocos Norte              21           103
6               nan            Ilocos Sur              23           174
7               nan              La Union              93           219
8               nan            Pangasinan             510          1040
10               II               Cagayan             152           404
..              ...                   ...             ...           ...
106             nan                PASMAK             236            20
107             nan           Quezon City             132            74
109  Central Office   Overseas Assessment             NaN           NaN
110             nan  Portfolio Assessment               3             8
111             nan                   RLA             NaN           NaN

    assessed_total certified_female certified_male certified_total  \
5              124               17             95             112
6              197               23            158             181
7              312               91            208             299
8             1550              473            969            1442
10             556              151            396             547
..             ...              ...            ...             ...
106            256              226             20             246
107            206              114             71             185
109              0              NaN            NaN               0
110             11                1              7               8
111              0              NaN            NaN               0

    certification_rate
5               0.9032
6               0.9188
7               0.9583
8               0.9303
10              0.9838
..                 ...
106             0.9609
107             0.8981
109                  0
110             0.7273
111                  0

[90 rows x 9 columns]

In [7]:
#filling down the region column with the appropriate values
df['region'] = df['region'].replace("nan", pd.NA).ffill()

print(df.head(10))

   region       province assessed_female assessed_male assessed_total  \
5       I   Ilocos Norte              21           103            124
6       I     Ilocos Sur              23           174            197
7       I       La Union              93           219            312
8       I     Pangasinan             510          1040           1550
10     II        Cagayan             152           404            556
11     II        Isabela              93           138            231
12     II  Nueva Vizcaya              94            95            189
13     II        Quirino              42            82            124
15    III         Aurora              46            70            116
16    III         Bataan              93           247            340

   certified_female certified_male certified_total certification_rate
5                17             95             112             0.9032
6                23            158             181             0.9188
7                91            208             299             0.9583
8               473            969            1442             0.9303
10              151            396             547             0.9838
11               88            137             225              0.974
12               87             91             178             0.9418
13               42             82             124                  1
15               40             64             104             0.8966
16               93            246             339             0.9971

In [8]:
print(df.dtypes)

region                object
province              object
assessed_female       object
assessed_male         object
assessed_total        object
certified_female      object
certified_male        object
certified_total       object
certification_rate    object
dtype: object

In [37]:
#change data types for numeric columns
numeric_columns = [
    "assessed_female",
    "assessed_male",
    "assessed_total",
    "certified_female",
    "certified_male",
    "certified_total"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")

df["certification_rate"] = pd.to_numeric(df["certification_rate"], errors="coerce")
df[["region", "province"]] = df[["region", "province"]].astype("str")

print(df.dtypes)

region                 object
province               object
assessed_female         Int64
assessed_male           Int64
assessed_total          Int64
certified_female        Int64
certified_male          Int64
certified_total         Int64
certification_rate    float64
dtype: object

In [28]:
#check for missing values in the dataset
print(df.isna().sum())

region                0
province              0
assessed_female       0
assessed_male         0
assessed_total        0
certified_female      0
certified_male        0
certified_total       0
certification_rate    0
dtype: int64

In [29]:
print(df[df["assessed_female"].isna()])

Empty DataFrame
Columns: [region, province, assessed_female, assessed_male, assessed_total, certified_female, certified_male, certified_total, certification_rate]
Index: []

In [30]:
print(type(df))
print(type(numeric_columns))

<class 'pandas.core.frame.DataFrame'>
<class 'list'>

In [31]:
#replace the missing values in the numeric columns with 0
df[numeric_columns] = df[numeric_columns].fillna(0)

In [32]:
print(df.isna().sum())

region                0
province              0
assessed_female       0
assessed_male         0
assessed_total        0
certified_female      0
certified_male        0
certified_total       0
certification_rate    0
dtype: int64

In [33]:
print(df["certification_rate"])

5      0.9032
6      0.9188
7      0.9583
8      0.9303
10     0.9838
        ...
106    0.9609
107    0.8981
109    0.0000
110    0.7273
111    0.0000
Name: certification_rate, Length: 90, dtype: float64

In [39]:
df.to_csv("C:\\Users\\Anna May\\Downloads\\FANRBF\\TVET_Stats_Analysis\\tvet_statistics_analysis\\data\\cleaned\\cleaned_tvet_data.csv", index=False)

## Data Cleaning Log — January 2021 TVET Assessment and Certification

**Source structure:** The source is a formatted statistical report with multi-row headers, region labels that are not repeated for each province, and regional subtotal rows.

**1 — Header normalization:** Replaced the multi-level report headers with unique column names for region, province, assessed counts by sex, certified counts by sex, and certification rate.

**2 — Region labels:** Filled down the region values so that each province-level record contains its corresponding region.

**3 — Regional subtotals:** Excluded rows labeled as regional totals from the province-level analytical table. These totals will be retained separately for reconciliation where appropriate.

**4 — Numeric conversion:** Converted count columns to integers where complete and valid, and converted certification rates to numeric percentage-point values. Investigated conversion failures before resolving them.

**5 — Zero and missing values:** Investigated zero counts and incomplete sex-specific values against the original source. Retained rows with missing values as zero counts.

**Limitations:** The report covers January 1–31, 2021. The data is a snapshot for a single reporting period and cannot, on its own, establish long-term trends.